### PR TITLE
Fixed all eslint warnings in tsx files

### LINKED ISSUE #146: Lots of tsx warnings on String quotes
All the strings in the codebase show a "Strings must use singlequote. eslintquotes" warning. 

They do not get cleared when I change the rules in `.eslintrc` to accommodate " as well

Looking for a solution and working on it, would love to get some pointers.

PS: This warning does not break the app, but it is a bit frustrating to see so many of these in the code

### PR DESCRIPTION
**Pull request by HariAcidReign**
Fixes #146 

**The problem:**
- ESLint was showing an error: `Strings must use singlequote.eslint(quotes)` which was particularly annoying because all the warnings were the same, and this made it very difficult to spot any other important errors in code.
- To make things worse, this was showing up in **almost every .tsx file**

**The solution:**
- Modifying the rules in `.eslintrc ` did not make the warnings go away
- Most of the warnings did go away on converting double quotes to single quotes, but that conversion will definitely cause problems in the future. Also, there are thousands of double quotes used everywhere, so it would be a pain to fix every one of them as well.
- So the best and the least messy option were to disable those specific warnings in every .tsx file that had double quotes in it, and that is exactly what I have done.

PS: Every component in the app had been checked after doing this change, and there is no problem in any of them.
PPS: Converting double quotes to Back ticks are not resolving this issue.

Open to suggestions, and willing to implement them immediately 🙌🏻

### CODE REVIEW

**Comment by flyingcircle** [comment]
Oh can you pull in latest, looks like it overlapped a little with another PR.

**Comment by HariAcidReign** [comment]
@flyingcircle One of the changes in PR #152 was the conversion of " to ' (as I had mentioned in my issue above). So that seemed to have caused a conflict. I've resolved it now. This PR will ensure that warning won't pop up when a double quote is used from now on anywhere in the code.

**Comment by flyingcircle** [comment]
Why would we disable a bunch of linting? That seems unnecessary to me.

**Comment by HariAcidReign** [comment]
@flyingcircle That lint warning came only for double quotes, so I decided to hide it instead of changing it into single quotes(and ensure that I solved the issue with the least amount of changes in code, and also allow double quotes to be used in the future without it causing a lint error) , that was my thought process. No problem, I'll work on some other issues 🚀

**Pull request closed without merging**
