### PR TITLE
chore: Fix broken URL

### PR DESCRIPTION
**Pull request by haruelrovix**
_Self explanatory._

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @haruelrovix can you rebase this PR from master? Changes to the readme can go straight to master

**Comment by haruelrovix** [comment]
@iRoachie Done, I think. _Never did `rebase` previously_ 🤞

**Comment by iRoachie** [comment]
@haruelrovix I think it may be easier if you make a new PR. This time when you create the branch make sure you do it from master

**Comment by haruelrovix** [comment]
@iRoachie 👉 #67

**Pull request closed without merging**
