### PR TITLE
added .prettierignore file and apply existing prettier rules in every file

### PR DESCRIPTION
**Pull request by NishargShah**
Apply `.prettier` rules in every `.tsx` file

### CODE REVIEW

**Comment by flyingcircle** [comment]
This has some merge conflicts, can you fix those up?

**Comment by NishargShah** [comment]
@flyingcircle I solved it please check

**Comment by flyingcircle** [comment]
Sorry, fix the conflicts one more time please.

**Comment by NishargShah** [comment]
@flyingcircle I solved all conflicts, please check now

**Pull request merged**
