### PR TITLE
fix broken url

### PR DESCRIPTION
**Pull request by badrshs**
the links of expo websites were pointing to v16.0.0 , but in general the links are not working any more
just change the url to latest version

### CODE REVIEW

**Review by xavier-villelegier — APPROVED** [review]
Good catch @badrshs, thanks 🔥

**Review by xavier-villelegier — CHANGES_REQUESTED** [review]
Ah you opened your PR on `master`. Could you open it on `next` please ?

**Comment by badrshs** [comment]
I didnt understand what exactly you need  😄 ?

**Comment by xavier-villelegier** [comment]
Your PR is based on the master branch, could you reopen it by doing the change on the ˋnext` branch ? 👌

**Comment by badrshs** [comment]
done  👌

**Pull request closed without merging**
