### PR TITLE
Fix strict mode enabled typescript issues

### PR DESCRIPTION
**Pull request by khushal87**
With this PR the following issues are fixed:

- Almost all of the **critical typescript issues** are solved in the app (when the strict mode is visible) except the input ref issue 
- Fixed the **critical ThemeReducer tsc** issue. 
- Also, I have fixed the **invalid Avatar image** which was not being fetched from the CDN. [The link was denied access.]
- Fixed invalid icons on the settings page

Reference: #201

### CODE REVIEW

**Comment by khushal87** [comment]
@flyingcircle @pranshuchittora Please review.

**Review by arpitBhalla — COMMENTED** [review]
🚀

**Review by arpitBhalla — COMMENTED** [review]
@khushal87 Seems good to me

**Comment by khushal87** [comment]
Thanks @arpitBhalla for the review.

**Pull request merged**
