### PR TITLE
Addition of Dialogs Page

### PR DESCRIPTION
**Pull request by Dhananjayan-PN**
## Summary
Upon implementation of the new Dialog component, introduced in this [Issue](https://github.com/react-native-elements/react-native-elements/issues/2910) and implemented in this [PR](https://github.com/react-native-elements/react-native-elements/pull/2911), I have incorporated this into the demo app with a new page dedicated to dialogs and their different types. Here's a quick look at what it looks like:

<p float="left">
  
   
  
</p>

<p float="left">
   
   
  
</p>

### CODE REVIEW

**Comment by flyingcircle** [comment]
That looks great. It looks like you tried to update the yarn.lock file, so now this is out of date.

**Comment by Dhananjayan-PN** [comment]
I just pulled the current yarn.lock file in the repository and pushed it to my fork. Ready to review!

**Comment by flyingcircle** [comment]
Same here, the lock file is off now.

**Comment by Dhananjayan-PN** [comment]
what would you suggest would be the best way to resolve this?

**Comment by Dhananjayan-PN** [comment]
Okay, I figured it out. I just fetched it from upstream. There are no more changes to yarn.lock in the PR

**Comment by Dhananjayan-PN** [comment]
Hey @flyingcircle! Kindly merge this PR along with https://github.com/react-native-elements/react-native-elements/pull/2911
Thanks!

**Pull request merged**
