### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by hetanthakkar**
There were few errors when trying to locally set up this repo. I fixed those errors

### CODE REVIEW

**Comment by HariAcidReign** [comment]
There are 2 overlaps with #212 that may cause merge conflict. Do check it out.
Btw I don't think this fixes all the errors as I tried it out in my fork and the errors still persist.

**Comment by HariAcidReign** [comment]
image

Attaching my error for reference. I'm actively trying to solve it but feel free to look into it as well.

**Comment by hetanthakkar** [comment]
@HariAcidReign try doing npm i before running your code !?

**Comment by HariAcidReign** [comment]
I used `yarn install` already. Is your fork working?

**Comment by hetanthakkar** [comment]
> I used `yarn install` already. Is your fork working?

absolutely fine!

**Pull request closed without merging**
