### PR TITLE
Addition of new Chip Showcase Page

### PR DESCRIPTION
**Pull request by Dhananjayan-PN**
Upon implementation of the new Chip component, I have incorporated this into the demo app with a new page dedicated to chips and their different types. Here's a quick look at what it looks like:

drawing

This PR is related to this Idea Proposal Issue (https://github.com/react-native-elements/react-native-elements/issues/2879)  and this Chip Component PR (https://github.com/react-native-elements/react-native-elements/pull/2890) on the RNE repository. 

Kindly review this PR. Looking forward to a merge :)

### CODE REVIEW

**Comment by flyingcircle** [comment]
6,000 lines changed in the yarn.lock file? Please don't do a full update on the lock file. Can you undo that change?

**Comment by Dhananjayan-PN** [comment]
Sure no problem!

**Comment by Dhananjayan-PN** [comment]
All Done! I replaced it with the one currently in the directory. Kindly review the changes :)

**Comment by flyingcircle** [comment]
I was about to test this out, but there's a conflicting file. Can you fix that?

**Comment by Dhananjayan-PN** [comment]
Sure! I'm on it!

**Comment by Dhananjayan-PN** [comment]
All done!

**Comment by flyingcircle** [comment]
I'm not able to get this to work. I keep hitting errors. You really need to remove all of those changes to the yarn.lock file

**Comment by Dhananjayan-PN** [comment]
I actually pulled the latest yarn.lock file from the RNE-app repo and pushed it into my branch. Let me see if I can fix it

**Comment by Dhananjayan-PN** [comment]
@flyingcircle Can you try now?

**Comment by Dhananjayan-PN** [comment]
So it seems like the current yarn.lock is different from when I cloned from this branch so it's yelling at me. Do let me know if you're running into errors with these changes.

**Comment by flyingcircle** [comment]
Are you actually running the code? I am hitting an error when trying to run this branch.

**Comment by Dhananjayan-PN** [comment]
Doesn't the Chip component have to be merged into the RNE repo to be able to test it out in the app with RNE as a dependency?

**Comment by Dhananjayan-PN** [comment]
So to test it, I swapped out the dependency to my forked RNE branch and it worked perfectly

**Comment by Dhananjayan-PN** [comment]
Should I be doing it any differently?

**Comment by flyingcircle** [comment]
```
AppLoading threw an unexpected error when loading:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CustomContentComponent`.
- node_modules/react-native/Libraries/LogBox/LogBox.js:148:8 in registerError
- node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
- node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
- node_modules/expo/build/environment/react-native-logs.fx.js:27:4 in error
- node_modules/expo-app-loading/build/AppLoading.js:10:13 in componentDidMount
- node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
- node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:14 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:30 in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```
I can build from other people's branches, just not yours. So there is something off here. I'd suggest trying to clean slate.

**Comment by flyingcircle** [comment]
And please don't change the yarn files, I know that I need to pull in your branch code, so no need to push that to your PR

**Pull request merged**
