### PR TITLE
Fixed critical typescript error and other issues

### PR DESCRIPTION
**Pull request by khushal87**
I have fixed almost half of the typescript errors which where critical for the application with this pull request. In the due time I observed several props and Components where used ineffectively example:

- Accessory in Avatar should be used as `Avatar.Accesory` while it was used as `Accessory` only(which was a bug/irrelevant).
- Removed `height, width and small` props from the Avatar as they where irrelevant.
- Confirm password `leftIcon` was imported as only `icon` which was again irrelevant and is now solved. So the icon is now rendered successfully. 
- Brought down **92 typescript errors count to 40 currently**.
- Some other observed issues are also fixed.

I want some suggestions and want to have a discussion for the other issues with you @flyingcircle . Thanks, I am waiting for your feedback and response and suggestions on how I can improve.

Related to issue - #145

### CODE REVIEW

**Comment by HariAcidReign** [comment]
@khushal87 @flyingcircle it seems this PR has caused some rendering problem with the `facebook-messenger` icon. Can anyone confirm the same?

**Comment by flyingcircle** [comment]
@HariAcidReign can you be more specific with an example?

**Comment by flyingcircle** [comment]
@HariAcidReign nevermind I see what you mean

**Comment by flyingcircle** [comment]
@HariAcidReign fixed.

**Pull request merged**
