### PR TITLE
Migrated Class based Components to Functional Components using hooks

### LINKED ISSUE #135: Toggle switch Button on Settings page doesn't work
The toggle switch button on Settings page doesn't work. I can find a potential fix for it.

### PR DESCRIPTION
**Pull request by khushal87**
Currently the app had irregular usage of Components types(Class based/Functional). Some of the components where Class based while others where Functional. Therefore, thinking about the uniformity I have migrated all the components to be used as functional. The components I have targeted in this PR is:

- components/Apploading.web.js
- lists/content.js
- lists/index.js
- login/index.js
- login/screen2.js
- buttons.js
- fonts.js
- header.js
- inputs.js
- pricing.js
- profile.js
- ratings.js
- settings.js
I have used traditional approach of hooks for certain tasks such as **useState**, **useEffect** for componentDidMount, **useRef** for reference in input. I am awaiting feedback and wish that this will be considered a meaningful pull request
Reference issue - https://github.com/react-native-elements/react-native-elements-app/issues/136
I have also fixed some other noticable issues, like unresponsive switch button in settings page(https://github.com/react-native-elements/react-native-elements-app/issues/135).

### CODE REVIEW

**Comment by flyingcircle** [comment]
I pulled in a bunch of PR's please update your code with the latest branch.

**Comment by khushal87** [comment]
Done @flyingcircle

**Comment by flyingcircle** [comment]
Looks Good Thanks!

**Comment by ArenaGrenade** [comment]
Wow! Did you just partially complete one of the ideas????? That is amazing work @khushal87. :tada:

**Comment by khushal87** [comment]
Thank you. But I don't think so. If it does I am really happy for it.

**Pull request merged**
