### PR TITLE
Fix touchable scale + Avatar placeholder

### PR DESCRIPTION
**Pull request by martinezguillaume**

### CODE REVIEW

**Review by iRoachie — APPROVED** [review]

**Comment by iRoachie** [comment]
Also fixes https://github.com/react-native-training/react-native-elements/issues/1700#issue-394987048

**Comment by iRoachie** [comment]
There's no `scaleProps` prop anymore on ListItem, the values are just spread in.

**Comment by iRoachie** [comment]
Hey @Monte9 just letting you know you'll have to deploy/publish this

**Comment by Monte9** [comment]
Thanks for the ping. Will publish in the next couple days.

**Comment by Monte9** [comment]
Published!

**Pull request merged**
